version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tech_blog
    ports:
      - 6060:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-ui:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 6061:80

volumes:
  postgres:
